// Supabase configuration
window.SUPABASE_URL = 'https://rqnrfsdftfmtkguezwxv.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbnJmc2RmdGZtdGtndWV6d3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNzk0OTcsImV4cCI6MjA4MTg1NTQ5N30.Iem0vrwR0cCqTA6XWXsob8GSPFWrBqOXs98KJKKYN3k';
